### PR TITLE
Add Pure GTK support (for use in Wayland)

### PR DESCRIPTION
**Pull request by kjinho**
#58

### CODE REVIEW

**Review by jistr — APPROVED** [review]
Installed the test build and it works well for me. You may want to clean up the commit history or the maintainer may perhaps wish to use the "squash and merge" option, but LGTM. :+1: Thanks!

**Comment by kjinho** [comment]
Thanks for testing it out, @jistr! I'm not familiar with best practices to clean up commit history, but if you have any resources I should look at for how I should do so, I would be happy to try.

Thanks again!

**Comment by jistr** [comment]
@kjinho It may not be the only way, but what i'd use for commit history cleanup is called interactive rebase. Among other things it allows squashing multiple commits into one. I don't have a good source on hand but if you put "git interactive rebase" into Google or Youtube, i hope helpful stuff would come up.

But i'm not sure if the cleanup is really necessary here, i think it depends on the review of the folks who have merge rights in this repo. I don't :slightly_smiling_face: .

**Comment by kjinho** [comment]
@jistr Thank you for the suggestions. I've tried the interactive rebase, but I think I may have just made things worse. I'll play around a bit and see what I can do to simplify things.

If necessary, I can always just start afresh with a clean repo and generate a new pull request. The changes are easy enough to implement.

**Comment by doskel** [comment]
hey all! was just wanting to play about with this, but couldn't get it to compile on my system with complaints about meson,build missing. should i just wait for it to get merged, or is there an easy solution i'm missing?

**Comment by kjinho** [comment]
> hey all! was just wanting to play about with this, but couldn't get it to compile on my system with complaints about meson,build missing. should i just wait for it to get merged, or is there an easy solution i'm missing?

@doskel Have you tried installing the test build? 

```
flatpak install --user https://dl.flathub.org/build-repo/93142/org.gnu.emacs.flatpakref
```

**Comment by doskel** [comment]
yeah, i gave that a go, but it just 404ed for me. i assume it was pruned?

**Comment by doskel** [comment]
this one's been open a while, so i figured i'd just @muep

**Comment by kjinho** [comment]
> hey all! was just wanting to play about with this, but couldn't get it to compile on my system with complaints about meson,build missing. should i just wait for it to get merged, or is there an easy solution i'm missing?

Did you pull the necessary submodules?

```git submodule update --init --recursive```

**Comment by kjinho** [comment]
> yeah, i gave that a go, but it just 404ed for me. i assume it was pruned?

@doskel I've created a new pull request for PGTK support. If you still have trouble building it yourself, try the test build there. #72

**Pull request closed without merging**
