### PR TITLE
Enable TLS support

### LINKED ISSUE #19: Spacemacs fails to start with error "Symbol's value as variable is void: \213"
Hi,

I tried to use [spacemacs](http://spacemacs.org/) with flatpak emacs and if I switch to `develop` branch, which is recommended, I'm hitting this issue:

```
Warning (initialization): An error occurred while loading ‘/home/zlopez/.emacs.d/init.el’:

Symbol's value as variable is void: \213

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

This could be related to https://github.com/syl20bnr/spacemacs/issues/11585. According to [discussion](https://github.com/syl20bnr/spacemacs/issues/11585#issuecomment-484531038) this issue is about missing `gnutls`. I looked at `freedesktop.Sdk` runtime and it looks like gnutls is not part of this runtime.

### PR DESCRIPTION
**Pull request by philn**
This is a requirement for the spacemacs develop branch.
See also: https://github.com/syl20bnr/spacemacs/issues/11585
Fixes #19

### CODE REVIEW

**Comment by muep** [comment]
Change by itself looks good. However, I am surprised that it is required - even current builds of Emacs in this flatpak are linked against gnutls.

Does the problem get addressed by installing the test build from https://github.com/flathub/org.gnu.emacs/pull/26#issuecomment-633241192 ?

**Comment by philn** [comment]
Yes I confirm the test build works. Spacemacs develop branch now works fine.

**Comment by muep** [comment]
I am a bit baffled that it does not work by default, when it clearly is doing something with gnutls already. But it should be reasonably safe to explicitly enable the support.

**Comment by muep** [comment]
Oh, and thank you @philn for providing a fix for it!

**Pull request merged**
