### PR TITLE
add tree-sitter support 

### PR DESCRIPTION
**Pull request by kjinho**
Adds tree-sitter support #63

### CODE REVIEW

**Review by muep — APPROVED** [review]
Looks good. Kicked the tires a bit as well, but I don't know the tree-sitter based modes all that good. I think the basics should be working, though.

@kjinho , do you think we should try something specific with this before merging?

**Comment by kjinho** [comment]
@muep, perhaps just trying the basics is enough:

1. Installing a tree-sitter language, like `bash`: `M-x treesit-install-language-grammar`
2. Opening up a bash file to edit and enabling `bash-ts-mode` to see if syntax-highlighting/font-locking is working: `M-x bash-ts-mode`
3. Confirm that the major-mode is bash-ts-mode: `M-: major-mode`

What do you think?

**Comment by muep** [comment]
I tried roughly those things yesterday with Go and JSON modes. Seemed to work okay enough. It seemed a bit tricky with the grammar installations, but I suppose that's just how things are right now.

**Comment by muep** [comment]
@kjinho does the repository let you merge this now that it has been reviewed, or is it restricted to maintainers only?

**Comment by kjinho** [comment]
@muep , I think it needs to be maintainers to merge; I only see an option to close the pull request.

**Pull request merged**
